MODULE keys

    '--- keycode_ext Keys ALT-CTRL -------------
    CONST EXT_ALT_DN AS UBYTE = 60
    CONST EXT_ALT_UP AS UBYTE = 188
    CONST EXT_CTRL_DN AS UBYTE = 58
    CONST EXT_CTRL_UP AS UBYTE = 186
    '--- keycode keys --------------------------
    CONST UP_ARROW_PRESSED AS UBYTE = 145
    CONST DN_ARROW_PRESSED AS UBYTE = 17
    CONST PAGE_DN_PRESSED AS UBYTE = 51
    CONST PAGE_UP_PRESSED AS UBYTE = 57
    '--- editing -------------------------------
    CONST LEFT_ARROW AS UBYTE = $4f
    CONST RIGHT_ARROW AS UBYTE = $59
    CONST UP_ARROW AS UBYTE = $53
    CONST DELETE AS UBYTE = $4c
    CONST INSERT AS UBYTE = $4b
    CONST BACKSPACE AS UBYTE = $0f
    CONST HOME AS UBYTE = $50
    CONST END_KEY AS UBYTE = $51

    '--- Up/Down hex codes ----------------------
    CONST Q_PRESSED AS UBYTE = $11
    CONST C_PRESSED AS UBYTE = $30
    CONST R_PRESSED AS UBYTE = $14
    CONST D_PRESSED AS UBYTE = $21
    CONST X_PRESSED AS UBYTE = $2f

    CONST E_PRESSED AS UBYTE = $13
    CONST F_PRESSED AS UBYTE = $22
    CONST L_PRESSED AS UBYTE = $27
    CONST M_PRESSED AS UBYTE = $34

    CONST V_PRESSED AS UBYTE = $31
    CONST U_PRESSED AS UBYTE = $17
    CONST T_PRESSED AS UBYTE = $15
    CONST P_PRESSED AS UBYTE = $1A
    CONST N_PRESSED AS UBYTE = $33
    CONST A_PRESSED AS UBYTE = $1f
    CONST G_PRESSED AS UBYTE = $23
    CONST S_PRESSED AS UBYTE = $20

    CONST ESC AS UBYTE = 27
    CONST CR AS UBYTE = 13
    CONST TAB AS UBYTE = 9

END MODULE